//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrelloAppV1._2
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AccountTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string AppKey { get; set; }
        public string Token { get; set; }
        public string ToolTip { get; set; }
    }
}
